[build]
  # Build command
  command = "npm run build"
  # Directory with build output
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optimize for China - Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Audio files caching
[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.wav"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Fonts caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# VITE_API_BASE_URL = "https://kuku-coach-api.onrender.com/api" 